name: Direct PR to Main Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run linting
        run: make lint
        
      - name: Run type checking
        run: make type-check
        
      - name: Run unit tests
        run: make test-unit
        
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body: '## Validation Results\n\n✅ This PR has passed all validation checks.\n\nPlease ensure your changes:\n- Have been fully tested\n- Include documentation updates\n- Follow our coding standards'
            });