name: PR Checks

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run formatting checks
      run: |
        python -m black --check src tests
        python -m isort --check src tests
        python -m ruff check src tests

    - name: Install dependencies for version check
      run: |
        pip install semver

    - name: Check for version bump
      run: |
        if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
          # Extract version from the PR branch
          PR_VERSION=$(grep -Po '(?<=__version__ = ")[^"]*' src/lluminary/version.py)
          echo "PR version: $PR_VERSION"

          # Checkout the base branch to compare version
          git checkout ${{ github.event.pull_request.base.ref }}
          MAIN_VERSION=$(grep -Po '(?<=__version__ = ")[^"]*' src/lluminary/version.py)
          echo "Main version: $MAIN_VERSION"

          # Compare versions using semver
          python -c "
          import semver

          pr_ver = semver.VersionInfo.parse('$PR_VERSION')
          main_ver = semver.VersionInfo.parse('$MAIN_VERSION')

          if pr_ver <= main_ver and '${{ github.event.pull_request.base.ref }}' == 'main':
            print('❌ Error: Version in PR branch ($PR_VERSION) must be higher than in main branch ($MAIN_VERSION)')
            exit(1)
          else:
            print('✅ Version correctly bumped from $MAIN_VERSION to $PR_VERSION')
          "
        else
          echo "Not merging to main, skipping version check"
        fi
